### ISSUE TITLE
Start implementing a system that can identify a single hero from a single image

### ISSUE THREAD

**Issue by mmunson2** [DaviidK/mercy-detector#4]

**Comment by DaviidK** [comment]
Currently working on this in the branch: M1-DavidTrainingClassifiers

**Comment by DaviidK** [comment]
The work on training classifiers is largely complete, and I've split that into a separate Project issue. See #21

**Comment by DaviidK** [comment]
This basic object identifier is being worked on in M1-UsingCascadeClassifiers
